snakefile: Snakefile
cores: 1
use-conda: True
conda-frontend: conda
#use-singularity: True
keep-going: True
jobs: 500
rerun-incomplete: True
#restart-times: 1
printshellcmds: True
executor: cluster-generic
cluster-generic-submit-cmd:
#cluster:
  mkdir -p ../results/00LOG/smk-logfiles &&
  sbatch
    --ntasks={resources.ntasks}
    --mem={resources.mem_mb}
    --time={resources.time}
    --cpus-per-task={resources.threads}
    --job-name=smk-{rule}
    --output=../results/00LOG/smk-logfiles/{rule}.%j.out
    --error=../results/00LOG/smk-logfiles/{rule}.%j.err
    --account=scw1641
    --qos=maxjobs500
#    --partition=c_compute_neuro1

default-resources:
  - ntasks=1
  - mem_mb=5000
  - time="3-00:00:00"
  - threads=1
